spring.application.name=ecom-Flipkart
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
management.endpoints.web.exposure.include=*
endpoint.health.show-details=always
info.env.enabled=true
management.endpoint.shutdown.enabled=true