spring.application.name=ecom-Flipkart
spring.h2.console.enabled=true


#H2-Database
#spring.datasource.url=jdbc:h2:mem:test
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=create

#PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5433/ecpmdb
spring.datasource.username=postgres
spring.datasource.password=jaga
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


#Spring Actuator
management.endpoints.web.exposure.include=*
endpoint.health.show-details=always
info.env.enabled=true
management.endpoint.shutdown.enabled=true