package com.app.ecomflipkart;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

@Service
public class UserService {

    @Autowired
    private UserRepository userRepository;

    //----Previously we don't have database so keep using this line.-------- List<User> userList = new ArrayList<>();
    //----Previously Id we explicitly autogenerated. ------- private Long nextId = 1L;

    public List<User> fetchAllUsers(){
        return userRepository.findAll();
    }

    public Optional<User> getUser(Long id){
        /*
          for(User user : userList){
            if (user.getId().equals(id)){
                return user;
            }
        }
        return null;
         */
        /*  -----Below we used stream
        return userList.stream().filter(user -> user.getId().equals(id)).findFirst();
         */
        return userRepository.findById(id);
    }

    public void addUser(User user){
        userRepository.save(user);
    }

    public boolean updateUser(Long id, User updatedUser){
        return /* userList.stream()
                .filter(user-> user.getId().equals(id))
                .findFirst() */
           userRepository.findById(id)
                .map(existedUser-> {
                    existedUser.setFirstName(updatedUser.getFirstName());
                    existedUser.setLastName(updatedUser.getLastName());
                    userRepository.save(existedUser);
                    return true;
                }).orElse(false);
    }
}
