package com.app.ecomflipkart.service;

import com.app.ecomflipkart.Dto.AddressDTO;
import com.app.ecomflipkart.Dto.UserRequest;
import com.app.ecomflipkart.Dto.UserResponse;
import com.app.ecomflipkart.model.Address;
import com.app.ecomflipkart.model.User;
import com.app.ecomflipkart.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

@Service
public class UserService {

    @Autowired
    private UserRepository userRepository;

    //----Previously we don't have database so keep using this line.-------- List<User> userList = new ArrayList<>();
    //----Previously Id we explicitly autogenerated. ------- private Long nextId = 1L;

    public List<UserResponse> fetchAllUsers(){
        return userRepository.findAll().stream()
                .map(this::mapToUserResponse)
                .collect(Collectors.toList());
    }

    public Optional<UserResponse> getUser(Long id){
        /*
          for(User user : userList){
            if (user.getId().equals(id)){
                return user;
            }
        }
        return null;
         */
        /*  -----Below we used stream
        return userList.stream().filter(user -> user.getId().equals(id)).findFirst();
         */
        return userRepository.findById(id).map(this::mapToUserResponse);
    }

    public void addUser(UserRequest userRequest){
        // user.setId(nextId++);
        User user = new User();
        updateUserFromRequest(user,userRequest);
        userRepository.save(user);
    }

    public boolean updateUser(Long id, UserRequest updatedUserRequest){
        return /* userList.stream()
                .filter(user-> user.getId().equals(id))
                .findFirst() */
           userRepository.findById(id)
                .map(existedUser-> {
                    updateUserFromRequest(existedUser, updatedUserRequest);
                    userRepository.save(existedUser);
                    return true;
                }).orElse(false);
    }

    private void updateUserFromRequest(User user, UserRequest userRequest){
        user.setFirstName(userRequest.getFirstName());
        user.setLastName(userRequest.getLastName());
        user.setEmail(userRequest.getEmail());
        user.setPhoneNumber(userRequest.getPhoneNumber());
        if (userRequest.getAddress() != null){
            Address address = new Address();
            address.setStreet(userRequest.getAddress().getStreet());
            address.setCity(userRequest.getAddress().getCity());
            address.setState(userRequest.getAddress().getState());
            address.setPinCode(userRequest.getAddress().getPinCode());
            user.setAddress(address);
        }
    }


/* ...........................USER TO USER RESPONSE MAPPER............................... */
    private UserResponse mapToUserResponse(User user){
        UserResponse response = new UserResponse();
        response.setId(String.valueOf(user.getId()));
        response.setFirstName(user.getFirstName());
        response.setLastName(user.getLastName());
        response.setEmail(user.getEmail());
        response.setPhoneNumber(user.getPhoneNumber());
        response.setRole(user.getRole());

        if (user.getAddress() != null){
            AddressDTO addressDTO = new AddressDTO();
            addressDTO.setStreet(user.getAddress().getStreet());
            addressDTO.setCity(user.getAddress().getCity());
            addressDTO.setState(user.getAddress().getState());
            addressDTO.setPinCode(user.getAddress().getPinCode());
            response.setAddress(addressDTO);
        }
        return response;
    }
}
